### Get all ToDo's
GET /api/todos
Host: localhost:8888
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzNkNzBhOGVkMGJhZTdjMWJmOTJlNzgiLCJuYW1lIjoiZWplbXBsbyIsImVtYWlsIjoiZWplbXBsb0BlamVtcGxvLmNvbSIsIl9fdiI6MCwiaWF0IjoxNjY1MDI4MTY2LCJleHAiOjE2NjUwMzE3NjZ9.CBpWE7oI8gamQsQ4xrcCiBcpTN5l3PS_8bzInO2vATQ

### Get specific ToDo
GET /api/todos/633e45e1ae592010e40646d3
Host: localhost:8888
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzNkNzBhOGVkMGJhZTdjMWJmOTJlNzgiLCJuYW1lIjoiZWplbXBsbyIsImVtYWlsIjoiZWplbXBsb0BlamVtcGxvLmNvbSIsIl9fdiI6MCwiaWF0IjoxNjY1MDI4MTY2LCJleHAiOjE2NjUwMzE3NjZ9.CBpWE7oI8gamQsQ4xrcCiBcpTN5l3PS_8bzInO2vATQ


### Post an ToDo
POST /api/todos
Host: localhost:8888
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzNkNzBhOGVkMGJhZTdjMWJmOTJlNzgiLCJuYW1lIjoiZWplbXBsbyIsImVtYWlsIjoiZWplbXBsb0BlamVtcGxvLmNvbSIsIl9fdiI6MCwiaWF0IjoxNjY1MDI4MTY2LCJleHAiOjE2NjUwMzE3NjZ9.CBpWE7oI8gamQsQ4xrcCiBcpTN5l3PS_8bzInO2vATQ
Content-Type: application/json

{"title":"titulo", "text": "texto"}

### Put a ToDo
PUT /api/todos/633e45e1ae592010e40646d3
Host: localhost:8888
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzNkNzBhOGVkMGJhZTdjMWJmOTJlNzgiLCJuYW1lIjoiZWplbXBsbyIsImVtYWlsIjoiZWplbXBsb0BlamVtcGxvLmNvbSIsIl9fdiI6MCwiaWF0IjoxNjY1MDI4MTY2LCJleHAiOjE2NjUwMzE3NjZ9.CBpWE7oI8gamQsQ4xrcCiBcpTN5l3PS_8bzInO2vATQ
Content-Type: application/json

{"title":"otro titulo", "text": "otro texto"}

### Delete a ToDo
DELETE /api/todos/633e50b5be51166159b67a34
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzNkNzBhOGVkMGJhZTdjMWJmOTJlNzgiLCJuYW1lIjoiZWplbXBsbyIsImVtYWlsIjoiZWplbXBsb0BlamVtcGxvLmNvbSIsIl9fdiI6MCwiaWF0IjoxNjY1MDI4MTY2LCJleHAiOjE2NjUwMzE3NjZ9.CBpWE7oI8gamQsQ4xrcCiBcpTN5l3PS_8bzInO2vATQ
Host: localhost:8888