### Get all users
GET /api/users
Host: localhost:8888

### Post an user
POST /api/users
Host: localhost:8888
Content-Type: application/json

{"name":"ejemplo", "email": "ejemplo@ejemplo.com", "password":"ejemplo"}

### Delete an user
DELETE /api/users/633e4f1fbeea226ec30a1d99
Host: localhost:8888